BEGIN;

ALTER TABLE tg_user DROP CONSTRAINT club;
ALTER TABLE tg_user ADD CONSTRAINT club FOREIGN KEY (club_id)
      REFERENCES clubs (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;


ALTER TABLE clubs DROP CONSTRAINT owner;
ALTER TABLE clubs ADD CONSTRAINT owner FOREIGN KEY (owner_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;


ALTER TABLE flights DROP CONSTRAINT pilot;
ALTER TABLE flights ADD CONSTRAINT pilot FOREIGN KEY (pilot_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE flights DROP CONSTRAINT co_pilot;
ALTER TABLE flights ADD CONSTRAINT co_pilot FOREIGN KEY (co_pilot_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE flights DROP CONSTRAINT club;
ALTER TABLE flights ADD CONSTRAINT club FOREIGN KEY (club_id)
      REFERENCES clubs (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE flights DROP CONSTRAINT flights_model_id_fkey;
ALTER TABLE flights ADD CONSTRAINT model FOREIGN KEY (model_id)
      REFERENCES models (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE flights DROP CONSTRAINT flights_takeoff_airport_id_fkey;
ALTER TABLE flights ADD CONSTRAINT takeoff_airport FOREIGN KEY (takeoff_airport_id)
      REFERENCES airports (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE flights DROP CONSTRAINT flights_landing_airport_id_fkey;
ALTER TABLE flights ADD CONSTRAINT landing_airport FOREIGN KEY (landing_airport_id)
      REFERENCES airports (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE SET NULL;

ALTER TABLE flights DROP CONSTRAINT flights_igc_file_id_fkey;
ALTER TABLE flights ADD CONSTRAINT igc_file FOREIGN KEY (igc_file_id)
      REFERENCES igc_files (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE followers DROP CONSTRAINT followers_destination_id_fkey;
ALTER TABLE followers ADD CONSTRAINT destination FOREIGN KEY (destination_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE followers DROP CONSTRAINT followers_source_id_fkey;
ALTER TABLE followers ADD CONSTRAINT source FOREIGN KEY (source_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE;


ALTER TABLE tracking_fixes DROP CONSTRAINT "tg_user.user_id";
ALTER TABLE tracking_fixes ADD CONSTRAINT pilot FOREIGN KEY (pilot_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE;

ALTER TABLE tracking_sessions DROP CONSTRAINT "tg_user.id";
ALTER TABLE tracking_sessions ADD CONSTRAINT pilot FOREIGN KEY (pilot_id)
      REFERENCES tg_user (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE CASCADE;

COMMIT;
