#!/bin/sh
exec 2>&1
set -e

DAEMON_USER=mapserver
DAEMON_GROUP=skylines
RUNDIR=/run/skylines
SCRIPT=/opt/skylines/src/mapserver.fastcgi
MAPFILE=/opt/skylines/src/mapserver/airspace/airspace.map
SOCKET=$RUNDIR/mapserver-fastcgi.socket

if [ ! -d "$RUNDIR" ]; then
    mkdir -m 775 $RUNDIR
    chgrp $DAEMON_GROUP $RUNDIR
fi

rm -f $SOCKET

export LANG=C
export LC_ALL=C

exec chpst -u$DAEMON_USER:www-data:$DAEMON_GROUP \
    $SCRIPT --socket=$SOCKET $MAPFILE
