#!/bin/sh
exec 2>&1
set -e

DAEMON_USER=tracking
DAEMON_GROUP=skylines
SCRIPT="/opt/skylines/src/manage.py tracking runserver"

export LANG=C
export LC_ALL=C

exec chpst -u$DAEMON_USER:$DAEMON_GROUP $SCRIPT
