# revision identifiers, used by Alembic.
revision = '1d8eda758ba6'
down_revision = '559cfc0613d2'

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_flight_path_chunks_flight_id', 'flight_path_chunks', ['flight_id'], unique=False)
    op.create_index('ix_tracking_fixes_pilot_id', 'tracking_fixes', ['pilot_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tracking_fixes_pilot_id', table_name='tracking_fixes')
    op.drop_index('ix_flight_path_chunks_flight_id', table_name='flight_path_chunks')
    ### end Alembic commands ###
