# revision identifiers, used by Alembic.
revision = '586691cd1352'
down_revision = '559cfc0613d2'

from alembic import op
import sqlalchemy as sa
from geoalchemy2.types import Geometry


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boundaries',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('time_created', sa.DateTime(), nullable=False),
                    sa.Column('time_modified', sa.DateTime(), nullable=False),
                    sa.Column('geometry', Geometry(geometry_type='MULTIPOLYGON', srid=4326), nullable=True),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('name_long', sa.String(), nullable=True),
                    sa.Column('abbrev', sa.String(), nullable=True),
                    sa.Column('iso_a2', sa.String(length=2), nullable=True),
                    sa.Column('iso_a3', sa.String(length=3), nullable=True),
                    sa.Column('region', sa.String(), nullable=True),
                    sa.Column('subregion', sa.String(), nullable=True),
                    sa.Column('continent', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boundaries')
    ### end Alembic commands ###
