#!/bin/sh
exec 2>&1
set -e

DAEMON_USER=skylines
DAEMON_GROUP=skylines
RUNDIR=/run/skylines
SCRIPT=/usr/local/bin/uwsgi
CONFIG=/opt/skylines/src/uwsgi/mapproxy_uwsgi.ini

if [ ! -d "$RUNDIR" ]; then
    mkdir -m 775 $RUNDIR
    chgrp $DAEMON_GROUP $RUNDIR
fi

export LANG=C
export LC_ALL=C

exec chpst -u$DAEMON_USER:www-data:$DAEMON_GROUP \
    $SCRIPT $CONFIG
